projectname                  = "lab"
region                       = "ap-southeast-1"
subnet-az                    = "ap-southeast-1a"
ami-id                       = "ami-094bbd9e922dc515d"
config-artifact-store        = "ec2-config-storage-3344"